# Generated by Django 4.2 on 2023-05-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=1000)),
                ('about_desc', models.CharField(max_length=1000)),
                ('about_img', models.ImageField(upload_to='about_img')),
            ],
        ),
        migrations.CreateModel(
            name='C_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(upload_to='course_img')),
                ('btn_subject', models.CharField(max_length=1000)),
                ('subject_name', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='D_advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='advisors')),
                ('img_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='E_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='events')),
                ('date', models.CharField(max_length=1000)),
                ('event_name', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('speaker', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='F_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='G_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='bookShop')),
                ('book_name', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='H_subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='I_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('experience', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
