# Generated by Django 4.2 on 2023-05-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_b_about_c_course_d_advisor_e_events_f_news_g_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_events',
            name='date_m_y',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
